"""
app/models/bom.py

SQLAlchemy ORM model for the `bom` table.

Source of truth: Supabase schema dump (tools/schema_dump.json)
Table name   : bom
Primary key  : bom_id (uuid)

Columns (exact match):
    bom_id        uuid        NOT NULL  PK
    deal_id       uuid        NULL      FK -> deals.deal_id
    vehicle_id    uuid        NULL      FK -> vehicle_master.vehicle_id
    total_cost    numeric     NULL
    margin        numeric     NULL
    generated_at  timestamp   NULL

Foreign keys TO this table:
    bom_items.bom_id -> bom.bom_id
"""

import uuid
from datetime import datetime
from decimal import Decimal

from sqlalchemy import DateTime, ForeignKey, Numeric
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database.database import Base


class BOM(Base):
    """ORM model for the `bom` table. Bill of Materials, generated by Paul."""

    __tablename__ = "bom"

    # ------------------------------------------------------------------
    # Primary Key
    # ------------------------------------------------------------------
    bom_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        nullable=False,
    )

    # ------------------------------------------------------------------
    # Columns — exact names and types from deployed schema
    # ------------------------------------------------------------------
    deal_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("deals.deal_id", ondelete="NO ACTION"),
        nullable=True,
    )
    vehicle_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("vehicle_master.vehicle_id", ondelete="NO ACTION"),
        nullable=True,
    )
    total_cost: Mapped[Decimal | None] = mapped_column(Numeric, nullable=True)
    margin: Mapped[Decimal | None] = mapped_column(Numeric, nullable=True)
    generated_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)

    # ------------------------------------------------------------------
    # Relationships
    # ------------------------------------------------------------------
    deal: Mapped["Deal"] = relationship(  # type: ignore[name-defined]
        "Deal",
        back_populates="boms",
        lazy="select",
    )
    vehicle: Mapped["VehicleMaster"] = relationship(  # type: ignore[name-defined]
        "VehicleMaster",
        back_populates="boms",
        lazy="select",
    )
    items: Mapped[list["BOMItem"]] = relationship(  # type: ignore[name-defined]
        "BOMItem",
        back_populates="bom",
        lazy="select",
    )

    def __repr__(self) -> str:
        return f"<BOM id={self.bom_id} deal={self.deal_id} cost={self.total_cost}>"
