"""
app/models/quotation.py

SQLAlchemy ORM model for the `quotations` table.

Source of truth: Supabase schema dump (tools/schema_dump.json)
Table name   : quotations
Primary key  : quotation_id (uuid)

Columns (exact match):
    quotation_id       uuid       NOT NULL  PK
    deal_id            uuid       NULL      FK -> deals.deal_id
    quotation_version  varchar    NULL
    subtotal           numeric    NULL
    discount           numeric    NULL
    tax                numeric    NULL
    grand_total        numeric    NULL
    quotation_status   varchar    NULL
    created_at         timestamp  NULL

Foreign keys TO this table:
    approvals.quotation_id -> quotations.quotation_id
    orders.quotation_id    -> quotations.quotation_id
    quotation_items.quotation_id -> quotations.quotation_id
"""

import uuid
from datetime import datetime
from decimal import Decimal

from sqlalchemy import DateTime, ForeignKey, Numeric, String
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database.database import Base


class Quotation(Base):
    """ORM model for the `quotations` table. Generated by Paul."""

    __tablename__ = "quotations"

    # ------------------------------------------------------------------
    # Primary Key
    # ------------------------------------------------------------------
    quotation_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        nullable=False,
    )

    # ------------------------------------------------------------------
    # Columns — exact names and types from deployed schema
    # ------------------------------------------------------------------
    deal_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("deals.deal_id", ondelete="NO ACTION"),
        nullable=True,
    )
    quotation_version: Mapped[str | None] = mapped_column(String, nullable=True)
    subtotal: Mapped[Decimal | None] = mapped_column(Numeric, nullable=True)
    discount: Mapped[Decimal | None] = mapped_column(Numeric, nullable=True)
    tax: Mapped[Decimal | None] = mapped_column(Numeric, nullable=True)
    grand_total: Mapped[Decimal | None] = mapped_column(Numeric, nullable=True)
    quotation_status: Mapped[str | None] = mapped_column(String, nullable=True)
    created_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)

    # ------------------------------------------------------------------
    # Relationships
    # ------------------------------------------------------------------
    deal: Mapped["Deal"] = relationship(  # type: ignore[name-defined]
        "Deal",
        back_populates="quotations",
        lazy="select",
    )
    items: Mapped[list["QuotationItem"]] = relationship(  # type: ignore[name-defined]
        "QuotationItem",
        back_populates="quotation",
        lazy="select",
    )
    approvals: Mapped[list["Approval"]] = relationship(  # type: ignore[name-defined]
        "Approval",
        back_populates="quotation",
        lazy="select",
    )
    orders: Mapped[list["Order"]] = relationship(  # type: ignore[name-defined]
        "Order",
        back_populates="quotation",
        lazy="select",
    )

    def __repr__(self) -> str:
        return (
            f"<Quotation id={self.quotation_id} "
            f"deal={self.deal_id} total={self.grand_total} "
            f"status={self.quotation_status!r}>"
        )
