import type { AgentJob, Deal, DealEvent } from '../types/deal'

const hoursAgo = (h: number) => new Date(Date.now() - h * 3600_000).toISOString()

export const mockDeals: Deal[] = [
  {
    id: 'DEAL-1042',
    org_name: 'Riverbend County Fire Dept.',
    vehicle_type: 'Type I Pumper',
    required_quantity: 2,
    city: 'Riverbend',
    country: 'USA',
    status: 'PENDING_APPROVAL',
    stage: 'APPROVAL',
    current_agent: 'VICTOR',
    lead_score: 91,
    confidence: 0.94,
    quotation_id: 'QT-1042',
    discount: 5,
    created_at: hoursAgo(30),
    updated_at: hoursAgo(28),
    approval_requested_at: hoursAgo(28),
    approval_sla_hours: 24,
  },
  {
    id: 'DEAL-1043',
    org_name: 'Cedar Hills EMS',
    vehicle_type: 'Type III Ambulance',
    required_quantity: 4,
    city: 'Cedar Hills',
    country: 'USA',
    status: 'REQUIREMENTS_COLLECTED',
    stage: 'REQUIREMENTS',
    current_agent: 'NEIL',
    lead_score: 78,
    confidence: 0.81,
    created_at: hoursAgo(10),
    updated_at: hoursAgo(2),
    approval_sla_hours: 24,
  },
  {
    id: 'DEAL-1044',
    org_name: 'Northbay Rescue Services',
    vehicle_type: 'Aerial Ladder Truck',
    required_quantity: 1,
    city: 'Northbay',
    country: 'USA',
    status: 'VALIDATED',
    stage: 'QUALIFICATION',
    current_agent: 'LISA',
    lead_score: 64,
    confidence: 0.58,
    created_at: hoursAgo(5),
    updated_at: hoursAgo(1),
    approval_sla_hours: 24,
  },
  {
    id: 'DEAL-1039',
    org_name: 'Port Adelaide Fire Brigade',
    vehicle_type: 'Type I Pumper',
    required_quantity: 3,
    city: 'Port Adelaide',
    country: 'AUS',
    status: 'ORDER_CREATED',
    stage: 'ORDER',
    current_agent: 'SALLY',
    lead_score: 88,
    confidence: 0.9,
    quotation_id: 'QT-1039',
    discount: 8,
    order_id: 'ORD-2039',
    created_at: hoursAgo(96),
    updated_at: hoursAgo(20),
    approval_sla_hours: 24,
  },
  {
    id: 'DEAL-1030',
    org_name: 'Millbrook Township',
    vehicle_type: 'Type III Ambulance',
    required_quantity: 2,
    city: 'Millbrook',
    country: 'USA',
    status: 'DELIVERED',
    stage: 'DELIVERY',
    current_agent: 'ADAM',
    lead_score: 82,
    confidence: 0.88,
    quotation_id: 'QT-1030',
    discount: 6,
    order_id: 'ORD-2030',
    delivery_status: 'DELIVERED',
    created_at: hoursAgo(240),
    updated_at: hoursAgo(4),
    approval_sla_hours: 24,
  },
  {
    id: 'DEAL-1027',
    org_name: 'Hartwell Volunteer FD',
    vehicle_type: 'Brush Truck',
    required_quantity: 1,
    city: 'Hartwell',
    country: 'USA',
    status: 'REJECTED',
    stage: 'REJECTED',
    current_agent: 'LISA',
    lead_score: 22,
    confidence: 0.31,
    rejection_reason: 'Budget below minimum fleet threshold; requirements could not be validated.',
    created_at: hoursAgo(70),
    updated_at: hoursAgo(65),
    approval_sla_hours: 24,
  },
  {
    id: 'DEAL-1051',
    org_name: 'Sable Point Fire District',
    vehicle_type: 'Type I Pumper',
    required_quantity: 1,
    city: 'Sable Point',
    country: 'USA',
    status: 'PENDING_APPROVAL',
    stage: 'APPROVAL',
    current_agent: 'VICTOR',
    lead_score: 85,
    confidence: 0.89,
    quotation_id: 'QT-1051',
    discount: 4,
    created_at: hoursAgo(55),
    updated_at: hoursAgo(53),
    approval_requested_at: hoursAgo(53),
    approval_sla_hours: 24,
  },
]

export const mockEvents: Record<string, DealEvent[]> = {
  'DEAL-1042': [
    { id: 'e1', deal_id: 'DEAL-1042', agent: 'MARTY', from_status: null, to_status: 'NEW_LEAD', message: 'Lead captured, scored 91/100', created_at: hoursAgo(30) },
    { id: 'e2', deal_id: 'DEAL-1042', agent: 'LISA', from_status: 'NEW_LEAD', to_status: 'VALIDATED', message: 'Requirements verified, confidence 0.94', created_at: hoursAgo(29.5) },
    { id: 'e3', deal_id: 'DEAL-1042', agent: 'NEIL', from_status: 'VALIDATED', to_status: 'REQUIREMENTS_COLLECTED', message: '2x Type I Pumper, delivery in 90 days', created_at: hoursAgo(29) },
    { id: 'e4', deal_id: 'DEAL-1042', agent: 'PAUL', from_status: 'REQUIREMENTS_COLLECTED', to_status: 'PRICED', message: 'Quote QT-1042 generated, 5% discount applied', created_at: hoursAgo(28.5) },
    { id: 'e5', deal_id: 'DEAL-1042', agent: 'VICTOR', from_status: 'PRICED', to_status: 'PENDING_APPROVAL', message: 'Sent to Victor for approval via Slack', created_at: hoursAgo(28) },
  ],
}

export const mockJobs: AgentJob[] = [
  {
    id: 'j1',
    deal_id: 'DEAL-1044',
    agent: 'LISA',
    endpoint: '/agents/lisa',
    status: 'FAILED',
    attempt: 2,
    max_attempts: 3,
    error_message: 'Timeout after 8000ms waiting on backend response',
    created_at: hoursAgo(1),
  },
  {
    id: 'j2',
    deal_id: 'DEAL-1043',
    agent: 'NEIL',
    endpoint: '/agents/neil',
    status: 'RETRYING',
    attempt: 1,
    max_attempts: 3,
    error_message: '502 from FastAPI container during redeploy',
    created_at: hoursAgo(2),
  },
  {
    id: 'j3',
    deal_id: 'DEAL-1039',
    agent: 'SALLY',
    endpoint: '/agents/sally',
    status: 'SUCCESS',
    attempt: 1,
    max_attempts: 3,
    created_at: hoursAgo(20),
  },
]
